<script context="module">
</script>

<script lang="ts">
	import './index.css';
</script>

<head>
	<title>Home</title>
</head>

<section class="info flex flex-col w-7/12  tracking-in-expand   mt-32 mx-auto">
	<div class="titles text-7xl text-white mb-4">
		<h1>Full-stack web developer,</h1>
		<h1>Automation engineer,</h1>
		<h1>Cloud expert</h1>
	</div>
	<p class="w-1/2 tracking-wide mb-4">
		Hey👋, i'm Mathias, a Norwegian based designer and computer engineer
		specializing in full-stack web development.
	</p>
	<a href="/services">
		<button class="btn btn-primary btn-outline w-[200px]">Learn more</button>
	</a>
</section>

<style lang="scss">
	@import url('https://fonts.googleapis.com/css2?family=Jost:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap');
	.info {
		/* font-family: 'Jost', sans-serif !important; */
	}
	.tracking-in-expand {
		-webkit-animation: tracking-in-expand 0.3s
			cubic-bezier(0.215, 0.61, 0.355, 1) both;
		animation: tracking-in-expand 0.7s cubic-bezier(0.215, 0.61, 0.355, 1) both;
	}
	/* ----------------------------------------------
 * Generated by Animista on 2022-7-11 9:43:53
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

	/**
 * ----------------------------------------
 * animation tracking-in-expand
 * ----------------------------------------
 */
	@-webkit-keyframes tracking-in-expand {
		0% {
			letter-spacing: -0.5em;
			opacity: 0;
		}
		40% {
			opacity: 0.6;
		}
		100% {
			opacity: 1;
		}
	}
	@keyframes tracking-in-expand {
		0% {
			letter-spacing: -0.5em;
			opacity: 0;
		}
		40% {
			opacity: 0.6;
		}
		100% {
			opacity: 1;
		}
	}
</style>
