<script context="module">
	import { gql, GraphQLClient } from 'graphql-request';
	import { variables } from '$lib/variables';
	export async function load() {
		const graphcms = new GraphQLClient(variables.GRAPH_CMS_URL, {
			headers: {}
		});

		const query = gql`
			query ProjectsIndex {
				projects {
					name
					description
					demo
					slug
					tags
					image {
						url
					}
				}
			}
		`;

		const { projects } = await graphcms.request(query);

		return {
			props: {
				projects
			}
		};
	}
</script>

<script lang="ts">
	export let projects: any;
</script>

<head>
	<title>Projects - Mathias Ödlund</title>
</head>
<section class="info  p-8 container mx-auto mt-12 flex flex-col gap-2 ">
	<div class="w-11/12 mx-auto mb-8 `">
		<h1 class="text-3xl text-[#ffffff] title ">Featured projects</h1>
		<p class="text-[#bfbfbf] info mt-2">
			A collection of featured freelancing projects that I have shipped recently
		</p>
	</div>
	{#each projects as project}
		<a href={project.demo}>
			<div
				class="container  w-full md:w-11/12 mx-auto p-4 rounded-md bg-base-300 shadow-lg slide-tr mt-4 md:mt-0 sm:mt-4"
			>
				<div
					class=" flex items-center  justify-center flex-col-reverse md:flex-row sm:flex-col-reverse"
				>
					<div class="avatar h-full ">
						<div class="w-full md:h-32 object-cover mr-4 mt-4 ">
							<img
								class="w-full object-cover rounded-md md:rounded-none sm:rounded-md"
								src={project.image[0].url}
								alt="image"
							/>
							{console.log(project.image.url)}
						</div>
					</div>
					<div
						class="flex flex-col items-center md:items-start sm:items-center"
					>
						<h1
							class="font-bold text-xl text-neutral title mb-3 md:mb-0 sm:mb-3"
						>
							{project.name}
						</h1>
						<p class="text-[#bfbfbf] info  tracking-wide">
							{project.description}
						</p>
						<div class="tags w-full flex  mt-2">
							{#each project.tags as tag}
								<a
									class="mr-3 outline-1 flex flex-row items-center justify-center px-1 rounded-sm outline text-primary"
								>
									{tag}
								</a>
							{/each}
						</div>
					</div>
				</div>
			</div>
		</a>
	{/each}
</section>

<!-- <pre>{JSON.stringify(projects, null, 2)}</pre> -->
<style>
	@import url('https://fonts.googleapis.com/css2?family=Jost:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap');

	/* ----------------------------------------------
 * Generated by Animista on 2022-7-11 8:39:55
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

	/**
 * ----------------------------------------
 * animation slide-tr
 * ----------------------------------------
 */
	.slide-tr {
		-webkit-animation: slide-tr 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
		animation: slide-tr 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
	}

	@keyframes slide-tr {
		0% {
			opacity: 0;
			-webkit-transform: translateY(30px) translateX(-30px);
			transform: translateY(30px) translateX(-30px);
		}

		100% {
			opacity: 100%;
			-webkit-transform: translateY(0) translateX(0);
			transform: translateY(0) translateX(0);
		}
	}
	.info {
		font-family: 'Jost', sans-serif !important;
	}
	.title {
		font-family: 'Jost', sans-serif;
	}
	.info {
		font-family: 'Jost', sans-serif;
	}
</style>
